name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
     # run: npm test # Ensure you have tests in place, or comment this line out

    - name: Build Docker image
      run: docker build -t hello-world-app .

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: hello-world-app
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker tag hello-world-app:latest 150387322390.dkr.ecr.ap-south-1.amazonaws.com/hello-world-app:latest
        docker push 150387322390.dkr.ecr.ap-south-1.amazonaws.com/hello-world-app:latest

    - name: Deploy to ECS
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-south-1
        IMAGE_TAG: ${{ github.sha }}
        ECR_REPOSITORY: hello-world-app
      run: |
        echo "Updating ECS service with new task definition..."
        aws ecs update-service --cluster hello-world-cluster --service hello-world-service --force-new-deployment
